### ISSUE TITLE
Please release with a license

### ISSUE THREAD

**Issue by dhandeo** [1xch/flask-celery-example#1]
Thank you very much for your initial skeleton.

I have forked this example, and added few experiments to it. I will like to push more commits there as I test more things, but I will really like if this whole example is released with some liberal license.

I suggest BSD or MIT or Apache v2 licenses.

That will motivate me and more developers on top of your seed.

Thank you,

:+1:

**Comment by 1xch** [comment]
Sure, this is open to do whatever you want with it. I added an MIT license.
